#! /bin/sh
### BEGIN INIT INFO
# Provides:          sowa
# Required-Start:    $local_fs $network $remote_fs
# Should-Start:      mysql
# Required-Stop:     $local_fs $network $remote_fs
# Should-Stop:       mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SOWA1
# Description:       SOWA1
### END INIT INFO


DIR="/home/pi/sowa"

PROCESS=`ps aux | grep -ie sowa.py | grep -v grep | awk '{print $2}' | sort -n | head -1`



case "$1" in
  start)
    if [ "$PROCESS" = "" ]; then
      echo "Uruchamianie serwera SOWA1..."
      cd $DIR
      nohup ./sowa.py >> ./log/error.log 2>&1 </dev/null &
    else
      echo "Serwer SOWA1 jest już uruchomiony."
    fi
    ;;
  stop)
    if [ "$PROCESS" != "" ]; then
      echo "Zatrzymywanie serwera SOWA1..."
      sudo kill -SIGTERM $PROCESS
      sleep 15
    else
      echo "Serwer SOWA1 nie jest uruchomiony."
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/sowa {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
